defaults: &defaults
  docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      environment:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
        RAILS_ENV: test
        RACK_ENV: test
  working_directory: ~/DocuTAP/www.clockwisemd.com
  shell: /bin/bash --login
  parallelism: 1

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: 'bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 '
      - run: bundle exec jekyll build
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ .Revision }}-{{ epoch }}
          paths:
          - vendor/bundle
          - _site
  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dep-{{ .Branch }}-{{ .Revision }}-
      - run: 'bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 '
      - run: 'ls -R _site'
      - run: 'ls _site/policies/index.html && bundle exec s3_website push'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only:
                - master
